### ISSUE TITLE
OOP-1-review-2022-10-16

### ISSUE THREAD

**Issue by hamerlinski** [Mlynek4/oop-put-course#1]
**Task 1**
- [ ] Proper communication/interaction between classes and objects is missing.
- [ ] Rename repository to **oop-put-course**
- [ ] Rename files to task1.cpp
- [ ] Format code properly - follow proper conventions e.g. [this](https://google.github.io/styleguide/cppguide.html)
